#pragma once

#include "slicer_core/geometry/OpenVdbLevelSetBuilder.h"

#include <cstdint>
#include <string>
#include <vector>

namespace slicer_core
{

/**
 * @brief Options for classifying an OpenVDB SDF into shell and interior regions.
 */
struct OpenVdbSurfaceShellOptions
{
    double shell_thickness_mm{0.10};
};

/**
 * @brief 3D classification masks for an OpenVDB surface shell prototype.
 */
struct OpenVdbSurfaceShellResult
{
    int width{0};
    int height{0};
    int depth{0};
    IndexBounds3D bounds;
    double shell_thickness_mm{0.10};
    std::vector<std::uint8_t> inside_mask;
    std::vector<std::uint8_t> shell_mask;
    std::vector<std::uint8_t> interior_mask;
    int inside_voxels{0};
    int shell_voxels{0};
    int interior_voxels{0};
    int outside_voxels{0};
    int outside_colored_voxels{0};
    int unclassified_voxels{0};
    std::vector<std::string> warnings;
    std::string error;
};

/**
 * @brief Classify a level set into inside, shell, and interior masks.
 * @param levelSet Level set generated by BuildOpenVdbLevelSet.
 * @param options Shell classification options.
 * @return Classification result.
 */
OpenVdbSurfaceShellResult ClassifyOpenVdbSurfaceShell(
    const OpenVdbLevelSetResult& levelSet,
    const OpenVdbSurfaceShellOptions& options);

/**
 * @brief Convert 3D mask coordinates to a flat vector index.
 * @param width Mask width.
 * @param height Mask height.
 * @param x Local X coordinate.
 * @param y Local Y coordinate.
 * @param z Local Z coordinate.
 * @return Flat vector index.
 */
std::size_t MaskIndex3D(int width, int height, int x, int y, int z);

}  // namespace slicer_core
